spring.application.name=payment-service
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
applyforme.paystack.secret.key=sk_test_e46089283b485ba9d19c3273838ddf8f6f4cc366
eureka.client.service-url.defaultZone=https://discovery-server-icoo.onrender.com/eureka
eureka.instance.prefer-ip-address=true
server.port=3000
spring.security.user.password=${SHARED_KEY}