spring.application.name=payment-service
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_database
spring.datasource.username=postgres
spring.datasource.password=damilare
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
applyforme.paystack.secret.key=sk_test_e46089283b485ba9d19c3273838ddf8f6f4cc366
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
server.port=3000
spring.security.user.password=${SHARED_INTERNAL_KEY}